# Generated by Django 4.2.10 on 2024-04-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='subcategories',
            options={'verbose_name': 'Subcategory', 'verbose_name_plural': 'Subcategories'},
        ),
        migrations.AlterModelTable(
            name='products',
            table='Product',
        ),
        migrations.AlterModelTable(
            name='subcategories',
            table='Subcategory',
        ),
    ]
